### ISSUE TITLE
Can you use custom markers?

### ISSUE THREAD

**Issue by chuckzezo** [ismyrnow/Leaflet.groupedlayercontrol#22]
Great plugin!

Is it possible to add custom markers for each overlay category or just in general? If so, where should this code go?

Thanks!

**Comment by ismyrnow** [comment]
I recommend taking a look at the custom marker example on the leaflet
website. Instead of adding each marker directly to the map, add the marker
to a layer group. You end up with slightly strange looking code like this:

```javascript
myLayerGroup.addLayer(myCustomMarker);
```

In Leaflet, both layers and markers implement a common interface: ILayer.
This means, you can create a layer group with an array of markers, or add
markers to an existing layer group.

So, your layer control will end up referencing the layer groups - which are
actually groups of markers!

**Comment by ismyrnow** [comment]
I recommend taking a look at the [custom marker example on the leaflet website](http://leafletjs.com/examples/custom-icons.html). Instead of adding each marker directly to the map, add the marker to a layer group.

In Leaflet, both layers and markers implement a common interface: ILayer. This means, you can create a layer group with an array of markers, or add markers to an existing layer group. You end up with slightly strange looking code like this:

```javascript
myLayerGroup.addLayer(myCustomMarker);
```

So, your layer control will end up referencing the layer groups - which are actually groups of markers!

**Comment by chuckzezo** [comment]
Thanks for the quick response, I'll give it a shot!

**Comment by chuckzezo** [comment]
Got it working... thanks for the help!

**Comment by chuckzezo** [comment]
Hey,

I think I spoke too soon about getting it to work 100%. My issue now is setting a default base layer map... I only have one. I fell like I'm close to getting it resolved, but keep missing the mark. Can you take a look at the below and tell me where I might be going wrong?

https://jsfiddle.net/chuckzezo/hxyp1y2w/

Thanks!

**Comment by ismyrnow** [comment]
Not sure if you deleted your last comment, but I got an email with a jsfiddle link in it. I made a few changes to get it to work. Most required fixing broken external resource links. The other was adding the basemap tile layer to the map.

https://jsfiddle.net/hxyp1y2w/4/

**Comment by chuckzezo** [comment]
I did get it working and I'm very happy with the result! Thanks again for
the quick response and awesome plugin!

**Comment by ismyrnow** [comment]
Glad to hear that!
